<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>اموال‌یار | نرم‌افزار مدیریت اموال و دارایی‌های سازمانی</title>
    <meta name="description" content="اموال‌یار نرم‌افزار یکپارچه مدیریت اموال و دارایی‌های سازمانی برای ثبت، پلاک‌گذاری، تحویل، انتقال، تعمیرات، انبارگردانی و گزارش‌گیری است.">
    <meta name="robots" content="index, follow, max-image-preview:large">
    <meta name="theme-color" content="#12141a">
    <link rel="canonical" href="https://amvalyar.ir/">
    <link rel="icon" type="image/svg+xml" href="{{ asset('branding/amvalyar-mark-original.svg') }}">
    <meta property="og:type" content="website">
    <meta property="og:locale" content="fa_IR">
    <meta property="og:site_name" content="اموال‌یار">
    <meta property="og:title" content="اموال‌یار | نرم‌افزار مدیریت اموال سازمانی">
    <meta property="og:description" content="مدیریت یکپارچه چرخه عمر دارایی؛ از ثبت و پلاک‌گذاری تا تحویل، انتقال، تعمیرات و انبارگردانی.">
    <meta property="og:url" content="https://amvalyar.ir/">
    <script type="application/ld+json">{"\u0040context":"https://schema.org","\u0040type":"WebSite","name":"اموال‌یار","alternateName":"AmvalYar","url":"https://amvalyar.ir/"}</script>
    <style>
        :root{--ink:#12141a;--muted:#626a7b;--line:#e7e9f1;--paper:#fafafe;--violet:#5b5cf0;--coral:#ff5a47;--mint:#dbf8ef}
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font-family:Tahoma,Arial,sans-serif;line-height:1.8}a{color:inherit}.shell{width:min(1180px,calc(100% - 40px));margin:auto}
        header{position:sticky;top:0;z-index:10;background:rgba(250,250,254,.88);backdrop-filter:blur(18px);border-bottom:1px solid rgba(18,20,26,.07)}nav{min-height:78px;display:flex;align-items:center;justify-content:space-between;gap:28px}.brand img{display:block;width:178px;height:auto}.links{display:flex;align-items:center;gap:28px}.links a{text-decoration:none;font-size:14px;font-weight:700}.button{display:inline-flex;align-items:center;justify-content:center;min-height:48px;padding:0 22px;border-radius:14px;background:var(--ink);color:#fff;text-decoration:none;font-weight:700;transition:.2s}.button:hover{transform:translateY(-2px);box-shadow:0 12px 30px rgba(18,20,26,.18)}.button.alt{background:var(--violet)}
        .hero{padding:92px 0 70px;overflow:hidden}.hero-grid{display:grid;grid-template-columns:1.05fr .95fr;align-items:center;gap:72px}.eyebrow{display:inline-flex;gap:9px;align-items:center;padding:7px 12px;border:1px solid #dcdcfb;border-radius:999px;background:#fff;color:#4546c8;font-size:13px;font-weight:700}.eyebrow:before{content:"";width:8px;height:8px;border-radius:50%;background:var(--coral)}h1{font-size:clamp(39px,5vw,68px);line-height:1.25;letter-spacing:-1.8px;margin:24px 0 22px;max-width:720px}.lead{font-size:18px;color:var(--muted);max-width:670px;margin:0 0 32px}.actions{display:flex;gap:12px;flex-wrap:wrap}.text-link{min-height:48px;padding:0 12px;display:inline-flex;align-items:center;text-decoration:none;font-weight:700}.proof{display:flex;gap:22px;flex-wrap:wrap;margin-top:30px;color:#4d5566;font-size:13px}.proof span:before{content:"✓";color:#159a72;font-weight:900;margin-left:7px}
        .visual{position:relative;min-height:485px;border-radius:34px;background:var(--ink);padding:28px;box-shadow:0 35px 80px rgba(34,34,77,.18);overflow:hidden}.visual:before{content:"";position:absolute;width:320px;height:320px;border-radius:50%;background:var(--violet);filter:blur(2px);left:-140px;top:-150px}.panel{position:relative;background:#fff;border-radius:22px;padding:22px;box-shadow:0 18px 55px rgba(0,0,0,.18)}.panel-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;font-weight:800}.dots{display:flex;gap:5px}.dots i{width:7px;height:7px;border-radius:50%;background:#d4d7e2}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.stat{padding:15px;border-radius:15px;background:#f4f4fa}.stat small{display:block;color:var(--muted);font-size:11px}.stat b{font-size:23px}.flow{position:relative;margin:18px 8px 5px;padding-right:22px;border-right:2px solid #e2e3ec}.flow div{position:relative;padding:11px 14px;margin:8px 0;background:#f8f8fc;border-radius:12px;font-size:12px}.flow div:before{content:"";position:absolute;right:-28px;top:17px;width:10px;height:10px;background:var(--violet);border:3px solid #fff;border-radius:50%}.asset-tag{position:absolute;left:22px;bottom:22px;width:190px;padding:17px;border-radius:18px;background:var(--mint);transform:rotate(-3deg);box-shadow:0 16px 35px rgba(0,0,0,.18)}.asset-tag strong{display:block}.asset-tag code{font-family:monospace;color:#246b59}.mark-float{position:absolute;right:28px;bottom:25px;width:92px;height:92px;padding:16px;border-radius:25px;background:#fff}
        section{padding:78px 0}.section-title{max-width:680px;margin-bottom:38px}.section-title p{color:var(--muted)}h2{font-size:clamp(29px,4vw,44px);line-height:1.35;margin:0 0 12px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card{background:#fff;border:1px solid var(--line);border-radius:22px;padding:26px;transition:.2s}.card:hover{transform:translateY(-4px);border-color:#c9c9f9;box-shadow:0 20px 45px rgba(37,39,70,.07)}.icon{display:grid;place-items:center;width:44px;height:44px;border-radius:13px;background:#ededff;color:var(--violet);font-weight:900;margin-bottom:20px}.card h3{margin:0 0 7px;font-size:18px}.card p{margin:0;color:var(--muted);font-size:14px}.band{padding:0 0 78px}.band-inner{display:grid;grid-template-columns:1fr auto;align-items:center;gap:32px;padding:42px;border-radius:28px;background:var(--ink);color:#fff}.band-inner p{margin:8px 0 0;color:#bfc4d3}.band .button{background:var(--coral)}footer{border-top:1px solid var(--line);padding:28px 0;color:var(--muted);font-size:13px}.foot{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}.foot img{width:132px}
        @media(max-width:900px){.hero-grid{grid-template-columns:1fr;gap:45px}.visual{min-height:440px}.cards{grid-template-columns:1fr 1fr}.links>a:not(.button){display:none}}@media(max-width:600px){.shell{width:min(100% - 26px,1180px)}nav{min-height:68px}.brand img{width:145px}.links{gap:8px}.links .button{min-height:42px;padding:0 14px}.hero{padding-top:58px}h1{font-size:39px}.visual{min-height:405px;padding:16px;border-radius:25px}.stats{grid-template-columns:1fr 1fr}.stats .stat:last-child{display:none}.asset-tag{width:160px}.cards{grid-template-columns:1fr}.band-inner{grid-template-columns:1fr;padding:28px}}
    </style>
</head>
<body>
<header><nav class="shell"><a class="brand" href="/" aria-label="اموال‌یار"><img src="{{ asset('branding/amvalyar-logo-original-light.svg') }}" alt="اموال‌یار"></a><div class="links"><a href="#features">قابلیت‌ها</a><a href="#workflow">چرخه دارایی</a><a class="button" href="{{ route('login') }}">ورود به سامانه</a></div></nav></header>
<main>
    <section class="hero"><div class="shell hero-grid"><div><span class="eyebrow">کنترل شفاف دارایی‌های سازمان</span><h1>نرم‌افزار مدیریت اموال و دارایی‌های سازمانی</h1><p class="lead">اموال‌یار تمام چرخه عمر دارایی را در یک جریان منسجم ثبت می‌کند؛ از ورود به انبار و پلاک‌گذاری تا تحویل، انتقال، تعمیرات، انبارگردانی و گزارش‌های مدیریتی.</p><div class="actions"><a class="button alt" href="{{ route('login') }}">ورود به پنل اموال‌یار</a><a class="text-link" href="#features">مشاهده قابلیت‌ها ←</a></div><div class="proof"><span>کنترل دسترسی سازمانی</span><span>تاریخچه قابل پیگیری</span><span>گزارش‌های عملیاتی</span></div></div>
        <div class="visual" aria-label="نمایی از جریان مدیریت دارایی"><div class="panel"><div class="panel-head"><span>مرکز کنترل دارایی</span><span class="dots"><i></i><i></i><i></i></span></div><div class="stats"><div class="stat"><small>دارایی فعال</small><b>۲۴۸</b></div><div class="stat"><small>در گردش</small><b>۱۸</b></div><div class="stat"><small>در تعمیر</small><b>۶</b></div></div><div class="flow" id="workflow"><div>ثبت و تخصیص کد دارایی</div><div>تحویل سازمانی با تأیید مسئول</div><div>ردیابی انتقال و گردش اموال</div></div></div><div class="asset-tag"><small>شناسه دارایی</small><strong>لپ‌تاپ واحد مالی</strong><code>AY-IT-0248</code></div><img class="mark-float" src="{{ asset('branding/amvalyar-mark-original.svg') }}" alt="نشان اموال‌یار"></div>
    </div></section>
    <section id="features"><div class="shell"><div class="section-title"><h2>هر دارایی، یک مسیر روشن</h2><p>اطلاعات پراکنده و فرم‌های کاغذی را به یک سیستم قابل پیگیری برای تیم اموال، انبار و مدیران تبدیل کنید.</p></div><div class="cards"><article class="card"><span class="icon">#</span><h3>کدگذاری و پلاک اموال</h3><p>تعریف الگوی کد، ثبت مشخصات و چاپ پلاک برای شناسایی دقیق هر دارایی.</p></article><article class="card"><span class="icon">↔</span><h3>تحویل و گردش دارایی</h3><p>ثبت تحویل، انتقال، عودت و زنجیره تأیید با تاریخچه‌ای شفاف و قابل استناد.</p></article><article class="card"><span class="icon">✓</span><h3>انبارگردانی هوشمند</h3><p>کنترل موجودی واقعی، مغایرت‌ها و وضعیت دارایی‌ها در سطح سازمان و شعب.</p></article><article class="card"><span class="icon">⌁</span><h3>تعمیرات و پیگیری</h3><p>مدیریت درخواست تعمیر، مسئول رسیدگی، وضعیت عملیات و زمان پاسخ‌گویی.</p></article><article class="card"><span class="icon">▦</span><h3>ساختار سازمانی</h3><p>تفکیک شرکت، واحد، محل، کاربر و نقش‌ها برای مدیریت امن چندسازمانی.</p></article><article class="card"><span class="icon">↗</span><h3>گزارش مدیریتی</h3><p>تصویر سریع و قابل اقدام از موجودی، ارزش، گردش و هشدارهای عملیاتی.</p></article></div></div></section>
    <section class="band"><div class="shell band-inner"><div><h2>دارایی‌های سازمان را قابل دیدن کنید.</h2><p>برای ورود به محیط امن مدیریت اموال از پنل سازمانی استفاده کنید.</p></div><a class="button" href="{{ route('login') }}">ورود به سامانه</a></div></section>
</main>
<footer><div class="shell foot"><img src="{{ asset('branding/amvalyar-logo-original-light.svg') }}" alt="اموال‌یار"><span>© {{ date('Y') }} اموال‌یار — سامانه مدیریت دارایی‌های سازمانی</span></div></footer>
</body>
</html>
